POST http://localhost:3000/get-virgil-jwt/ HTTP/1.1
Authorization: Bearer cardId.unixTimestamp.signature(cardId.unixTimestamp)
Content-Type: application/json

{
    "identity": "test"
}

Response: ICard

###
POST http://localhost:3000/get-twilio-jwt/ HTTP/1.1
Authorization: Bearer cardId.unixTimestamp.signature(cardId.unixTimestamp)
Content-Type: application/json

{
    "identity": "test"
}

Response:
{
    "token": "string"
}


###
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "card": RawSignedModel.exportAsJson()
}

Response:
{
    "token": "string"
}
