POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "rawCard": RawSignedModel.exportAsJson()
}

Response:
{
    "virgil_card": cardManager.exportCardAsJson(card);
}

###
POST http://localhost:3000/signin HTTP/1.1
Content-Type: application/json

{
    "identity": "string"
}

Response:
{
    "virgil_card": cardManager.exportCardAsJson(card);
}

###
POST http://localhost:3000/get-virgil-jwt/ HTTP/1.1
Authorization: Bearer cardId.unixTimestamp.signature(cardId.unixTimestamp)
Content-Type: application/json

{
    "identity": "test"
}

Response:
{
    "token": "string"
}

###
POST http://localhost:3000/get-twilio-jwt/ HTTP/1.1
Authorization: Bearer cardId.unixTimestamp.signature(cardId.unixTimestamp)
Content-Type: application/json

{
    "identity": "test"
}

Response:
{
    "token": "string"
}


