platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/twilio/cocoapod-specs'

target 'VirgilTwilioChat' do
  pod 'VirgilSDK', '~>3.2'
  pod 'SlackTextViewController'
  pod 'XAsync', '~>2.0'
  pod 'TwilioIPMessagingClient', '~> 0.14.0'
end